# Generated by Django 5.1.1 on 2024-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_identifier_payments_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='ident',
            field=models.TextField(editable=False, max_length=10, unique=True),
        ),
    ]
